services:
    # EventSubscriber
    ezplatform.view_cache.response_subscriber:
        class: EzSystems\PlatformHttpCacheBundle\EventSubscriber\HttpCacheResponseSubscriber
        arguments:
            - '@ezplatform.view_cache.response_configurator'
            - '@ezplatform.view_cache.response_tagger.dispatcher'
        tags:
            - { name: kernel.event_subscriber }

    ezplatform.x_location_id.response_subscriber:
        class: EzSystems\PlatformHttpCacheBundle\EventSubscriber\XLocationIdResponseSubscriber
        arguments: ['@fos_http_cache.http.symfony_response_tagger', '@ezpublish.api.repository']
        tags:
            - { name: kernel.event_subscriber }

    ezplatform.rest_cache_tagging.view_subscriber:
        class: EzSystems\PlatformHttpCacheBundle\EventSubscriber\RestKernelViewSubscriber
        arguments: ['@fos_http_cache.http.symfony_response_tagger']
        tags:
            - { name: kernel.event_subscriber }

    ezplatform.user_context_tagger.response_subscriber:
        class: EzSystems\PlatformHttpCacheBundle\EventSubscriber\UserContextSubscriber
        arguments: ['@ezplatform.http_cache.repository_tag_prefix', '%fos_http_cache.tag_handler.response_header%']
        tags:
            - { name: kernel.event_subscriber }

    ezplatform.hidden_location.exception_subscriber:
        class: EzSystems\PlatformHttpCacheBundle\EventSubscriber\HiddenLocationExceptionSubscriber
        arguments: ['@ezplatform.view_cache.response_tagger.location', '@ezplatform.view_cache.response_tagger.content_info']
        tags:
            - { name: kernel.event_subscriber }

    EzSystems\PlatformHttpCacheBundle\EventSubscriber\UserContextSiteAccessMatchSubscriber:
        decorates: ezpublish.siteaccess_match_listener
        arguments:
            - '@EzSystems\PlatformHttpCacheBundle\EventSubscriber\UserContextSiteAccessMatchSubscriber.inner'
            - '@fos_http_cache.user_context.request_matcher'
        tags:
            - { name: kernel.event_subscriber }

    EzSystems\PlatformHttpCacheBundle\EventSubscriber\RequestEventSubscriber:
        arguments:
            - "@=container.getParameter('fos_http_cache.event_listener.user_context.options')['user_hash_header']"
        tags:
            - { name: kernel.event_subscriber }

    # ResponseConfigurator
    ezplatform.view_cache.response_configurator:
        class: EzSystems\PlatformHttpCacheBundle\ResponseConfigurator\ConfigurableResponseCacheConfigurator
        arguments:
            - '$content.view_cache$'
            - '$content.ttl_cache$'
            - '$content.default_ttl$'
            - '@fos_http_cache.http.symfony_response_tagger'

    # ResponseTagger dispatcher
    ezplatform.view_cache.response_tagger.dispatcher:
        class: EzSystems\PlatformHttpCacheBundle\ResponseTagger\Delegator\DispatcherTagger
        # Taggers are added by a compiler pass
        arguments:
            - []

    # ResponseTagger proxy/extract
    ezplatform.view_cache.response_tagger.content_value_view:
        class: EzSystems\PlatformHttpCacheBundle\ResponseTagger\Delegator\ContentValueViewTagger
        arguments: ['@ezplatform.view_cache.response_tagger.content_info']
        tags:
            - {name: ezplatform.cache_response_tagger}

    ezplatform.view_cache.response_tagger.location_value_view:
        class: EzSystems\PlatformHttpCacheBundle\ResponseTagger\Delegator\LocationValueViewTagger
        arguments: ['@ezplatform.view_cache.response_tagger.location']
        tags:
            - {name: ezplatform.cache_response_tagger}

    # ResponseTagger value handlers
    ezplatform.view_cache.response_tagger.abstract_value:
        abstract: true
        arguments: ['@fos_http_cache.http.symfony_response_tagger']

    ezplatform.view_cache.response_tagger.content_info:
        class: EzSystems\PlatformHttpCacheBundle\ResponseTagger\Value\ContentInfoTagger
        parent: ezplatform.view_cache.response_tagger.abstract_value
        tags:
            - {name: ezplatform.cache_response_tagger}

    ezplatform.view_cache.response_tagger.location:
        class: EzSystems\PlatformHttpCacheBundle\ResponseTagger\Value\LocationTagger
        parent: ezplatform.view_cache.response_tagger.abstract_value
        tags:
            - {name: ezplatform.cache_response_tagger}

    # Twig
    ezplatform.view_cache.twig_extension:
        class: EzSystems\PlatformHttpCacheBundle\Twig\ContentTaggingExtension
        arguments:
            - '@ezplatform.view_cache.response_tagger.dispatcher'
            - '@fos_http_cache.http.symfony_response_tagger'
        tags:
            - {name: twig.extension}
